django_tasker_account/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.ConfirmEmail, 'confirm_email')
register_converter(converters.ChangePassword, 'change_password')
register_converter(converters.OAuth, 'oauth')

app_name = 'django_tasker_account'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('forgot_password/', views.forgot_password, name="forgot_password"),
    path('confirm/email/<confirm_email:data>/', views.confirm_email, name="confirm_email"),
    path('change/password/<change_password:data>/', views.change_password, name="change_password"),

    path('oauth/yandex/', views.oauth_yandex, name="oauth_yandex"),
    path('oauth/google/', views.oauth_google, name="oauth_google"),
    path('oauth/vk/', views.oauth_vk, name="oauth_vk"),
    path('oauth/facebook/', views.oauth_facebook, name="oauth_facebook"),
    path('oauth/facebook/deactivate/', views.oauth_facebook_deactivate, name="oauth_facebook_deactivate"),
    path('oauth/mailru/', views.oauth_mailru, name="oauth_mailru"),
    path('oauth/completion/<oauth:data>/', views.oauth_completion, name="oauth_completion"),

    path('profile/', views.profile, name="profile"),
    path('profile/change/password/', views.profile_change_password, name="profile_change_password"),
    path('profile/mylocation/', views.profile_mylocation, name="profile_mylocation"),
    path('profile/avatar/', views.profile_avatar, name="profile_avatar"),
]

django_tasker_account/models.py
import re
from os import urandom
from pathlib import Path

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _, get_supported_language_variant
from django.db import models
from django.contrib.auth.models import User
from django_tasker_geobase import models as geobase_models

from . import validators


class Profile(models.Model):

    GENDER = [
        (1, _('Male')),
        (2, _('Female')),
    ]

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name=_("User")
    )

    language = models.CharField(
        max_length=255,
        choices=settings.LANGUAGES,
        verbose_name=_("Language"),
        default=get_supported_language_variant(getattr(settings, 'LANGUAGE_CODE', 'en-US'), strict=False)
    )

    gender = models.SmallIntegerField(
        choices=GENDER,
        null=True,
        blank=True,
        verbose_name=_("Gender")
    )

    birth_date = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Birth date")
    )

    phone = models.BigIntegerField(
        null=True,
        blank=True,
        validators=[validators.mobile_number],
        verbose_name=_("Mobile phone"),
    )

    geobase = models.ForeignKey(
        geobase_models.Geobase,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name=_("Geobase")
    )

    def path(self, filename):
        extension = Path(filename).suffix
        key = urandom(16).hex()
        result = re.match(r'([a-z0-9]{2})([a-z0-9]{2})', key)
        return 'avatar/{0}/{1}/{2}'.format(result.group(1), result.group(2), key + extension)

    avatar = models.ImageField(upload_to=path, null=True, blank=True)

    def __str__(self):
        return 'User profile {user}'.format(user=self.user)


class Oauth(models.Model):
    PROVIDER = (
        (1, 'Google'),
        (2, 'Yandex'),
        (3, 'Mail.ru'),
        (4, 'VK.com'),
        (5, 'Facebook'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("User"))
    oauth_id = models.CharField(max_length=255, verbose_name=_("Oauth ID"))
    provider = models.IntegerField(choices=PROVIDER, verbose_name=_("Server"))

    access_token = models.CharField(max_length=255, verbose_name=_("Access token"))
    expires_in = models.DateTimeField(verbose_name=_("Expires date"))

    class Meta:
        unique_together = (('oauth_id', 'provider'),)
        verbose_name = _("OAuth")
        verbose_name_plural = _("OAuth")

    def __str__(self):
        return '%s %s' % (self.provider, self.user)

# Signals
@receiver(post_save, sender=User)
def account_profile(instance=None, created=None, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        profile = Profile.objects.filter(user=instance)
        if not profile.count():
            Profile.objects.create(user=instance)

    instance.profile.save()

django_tasker_account/views.py
import logging
import os
import re
import requests
import base64
import hashlib
import hmac
import json

from importlib import import_module
from urllib.parse import urlencode
from datetime import datetime, timedelta, timezone
from ipaddress import ip_address as ip_address_obj

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.core.files.storage import default_storage
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

from email_validator import validate_email
from django_tasker_geobase import geocoder


from . import forms, converters, models

logger = logging.getLogger('tasker_account')


def login(request: WSGIRequest):
    """View for user authentication"""
    if request.method == 'GET':
        return render(request, "django_tasker_account/login.html", {'form': forms.Login()})

    form = forms.Login(data=request.POST, request=request)
    if form.is_valid():
        user = form.login()
        logger.info("Login user username:{username}".format(username=user.username))
        return redirect(request.GET.get('next', settings.LOGIN_REDIRECT_URL))

    return render(request, 'django_tasker_account/login.html', {'form': form}, status=400)


def logout(request: WSGIRequest):
    if request.user.is_authenticated:
        logger.info("Logout user username:{username}".format(username=request.user.username))
        auth.logout(request)

    return redirect('/')


def signup(request: WSGIRequest):
    """View for user registration"""
    if request.method == 'GET':
        return render(request, "django_tasker_account/signup.html", {'form': forms.Signup()})

    form = forms.Signup(data=request.POST, request=request)
    if form.is_valid():
        form.confirmation()
        messages.success(request, _("A confirmation email has been sent to your email address"))
        return redirect(settings.LOGIN_URL)

    return render(request, "django_tasker_account/signup.html", {'form': form}, status=400)


def confirm_email(request: WSGIRequest, data: converters.ConfirmEmail):
    """View for confirmation email address"""
    form = forms.Signup(data={
        'username': data.username,
        'last_name': data.last_name,
        'first_name': data.first_name,
        'email': data.email,
        'password1': data.password1,
        'password2': data.password2,
    })

    if form.is_valid():
        user = form.save()
        data.session.delete()
        auth.login(request, user)

        # Set language profile
        # user.profile.language = get_supported_language_variant(get_language_from_request(request))

        # save geobase
        ip = request.META.get('HTTP_X_FORWARDED_FOR')
        if ip:
            ip = ip_address_obj(address=ip.split(',')[0])
        else:
            ip = ip_address_obj(address=request.META.get('REMOTE_ADDR'))

        if ip.is_global:
            geobase = geocoder.ip(request=request)

            # get locality
            locality = geobase.get(geo_type=4)
            if locality:
                user.profile.geobase = locality
                user.profile.save()

        messages.success(request, _("Your address has been successfully verified"))
        return redirect(data.next)

    return redirect(settings.LOGIN_URL)


def forgot_password(request: WSGIRequest):
    """View forgot password"""
    if request.method == 'GET':
        return render(request, "django_tasker_account/forgot_password.html", {'form': forms.ForgotPassword()})

    form = forms.ForgotPassword(data=request.POST, request=request)
    if form.is_valid():
        form.sendmail()
        messages.success(request, _("Password reset sent"))
        return redirect(settings.LOGIN_URL)

    return render(request, "django_tasker_account/forgot_password.html", {'form': form}, status=400)


def change_password(request: WSGIRequest, data: converters.ChangePassword):
    """Password change view"""
    if request.method == 'GET':
        form = forms.ChangePassword(user=data.user_id)
        return render(request, "django_tasker_account/change_password.html", {'form': form})

    form = forms.ChangePassword(data=request.POST, request=request, user=data.user)
    if form.is_valid():
        form.save()
        form.login()
        data.session.delete()
        messages.success(request, _("Password reset complete"))
        return redirect(data.next)

    return render(request, "django_tasker_account/change_password.html", {'form': form}, status=400)


def oauth_google(request: WSGIRequest):
    client_id = getattr(settings, 'OAUTH_GOOGLE_CLIENT_ID', os.environ.get('OAUTH_GOOGLE_CLIENT_ID'))
    client_secret = getattr(settings, 'OAUTH_GOOGLE_SECRET_KEY', os.environ.get('OAUTH_GOOGLE_SECRET_KEY'))

    if not client_id:
        logger.error(_("Application OAuth Google is disabled"))
        messages.error(request, _("Application OAuth Google is disabled"))
        return redirect('/')

    redirect_uri = "{shema}://{host}{path}".format(
        shema=request.META.get('HTTP_X_FORWARDED_PROTO', request.scheme),
        host=request.get_host(),
        path=request.path,
    )

    if not request.GET.get('code'):
        params = {
            'client_id': client_id,
            'redirect_uri': redirect_uri,
            'response_type': 'code',
            'state': request.GET.get('next', '/'),
            'scope': 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',
        }

        redirect_url = "https://accounts.google.com/o/oauth2/v2/auth?{param}".format(param=urlencode(params))
        return redirect(redirect_url)

    data = {
        'grant_type': 'authorization_code',
        'code': request.GET.get('code'),
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': redirect_uri,
    }

    response = requests.post('https://www.googleapis.com/oauth2/v4/token', data=data)
    json = response.json()

    response_info = requests.get(
        url='https://www.googleapis.com/oauth2/v1/userinfo',
        params={'format': 'json'},
        headers={'Authorization': 'OAuth ' + json.get('access_token')})

    json_info = response_info.json()

    session_store = import_module(settings.SESSION_ENGINE).SessionStore
    session = session_store()

    m = hashlib.sha256()
    m.update(str(json_info.get('id')).encode("utf-8"))

    dt = datetime.now(timezone.utc) + timedelta(seconds=json.get('expires_in'))

    session["oauth"] = {
        'provider': 1,
        'id': m.hexdigest(),
        'access_token': json.get('access_token'),
        'birth_date': None,
        'gender': None,
        'avatar': json_info.get('picture'),
        'last_name': json_info.get('family_name'),
        'first_name': json_info.get('given_name'),
        'username': None,
        'module': __name__,
        'expires_in': dt.isoformat(),
        'next': request.GET.get('state')
    }

    if json_info.get('verified_email'):
        email = json_info.get('email').strip().lower()
        user = email.rsplit('@', 1)[0]

        if validate_email(email).get('domain') != 'gmail.com':
            messages.error(request, _('Allowed to use for authorization domain gmail.com'))
            return redirect(settings.LOGIN_URL)

        user = str(user).replace(".", "_")
        if not models.User.objects.filter(username=user).exists():
            session["oauth"]["username"] = user

        session["oauth"]["email"] = email

    session.create()
    return redirect(reverse('django_tasker_account:oauth_completion', kwargs={'data': session.session_key}))


def oauth_yandex(request: WSGIRequest):
    client_id = getattr(settings, 'OAUTH_YANDEX_CLIENT_ID', os.environ.get('OAUTH_YANDEX_CLIENT_ID'))
    client_secret = getattr(settings, 'OAUTH_YANDEX_SECRET_KEY', os.environ.get('OAUTH_YANDEX_SECRET_KEY'))

    if not client_id:
        logger.error(_("Application OAuth Yandex is disabled"))
        messages.error(request, _("Application OAuth Yandex is disabled"))
        return redirect('/')

    redirect_uri = "{shema}://{host}{path}".format(
        shema=request.META.get('HTTP_X_FORWARDED_PROTO', request.scheme),
        host=request.get_host(),
        path=request.path,
    )

    if request.GET.get('error'):
        logger.error(_("User denied access to data"))
        messages.error(request, _("User denied access to data"))
        return redirect(settings.LOGIN_URL)

    if not request.GET.get('code'):
        params = {
            'client_id': client_id,
            'redirect_uri': redirect_uri,
            'response_type': 'code',
            'state': request.GET.get('next', '/'),
        }

        if settings.DEBUG:
            params['force_confirm'] = 'yes'

        return redirect('https://oauth.yandex.ru/authorize?' + urlencode(params))

    data = {
        'grant_type': 'authorization_code',
        'code': request.GET.get('code'),
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': redirect_uri,
    }

    response = requests.post('https://oauth.yandex.ru/token', data=data)
    json = response.json()

    response_info = requests.get(
        url='https://login.yandex.ru/info',
        params={'format': 'json'},
        headers={'Authorization': 'OAuth ' + json.get('access_token')},
    )

    json_info = response_info.json()

    session_store = import_module(settings.SESSION_ENGINE).SessionStore
    session = session_store()

    m = hashlib.sha256()
    m.update(str(json_info.get('id')).encode("utf-8"))

    dt = datetime.now(timezone.utc) + timedelta(seconds=json.get('expires_in'))

    session["oauth"] = {

django_tasker_account/templates/django_tasker_account/base.html
{% load i18n %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Kostya Ten">
        <title>Django Tasker Account</title>
        <!-- <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/floating-labels/"> -->
        <!-- Bootstrap core CSS -->
        <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="https://getbootstrap.com/docs/4.0/examples/floating-labels/floating-labels.css" rel="stylesheet">

        <link rel="stylesheet" href="https://d1azc1qln24ryf.cloudfront.net/114779/Socicon/style-cf.css?u8vidh">
    </head>
    <body>
        <div class="container">
            {% if request.user.is_authenticated %}
            <div class="row">
                <ul class="nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'django_tasker_account:profile' %}">{% trans "Personal info" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'django_tasker_account:profile_change_password' %}">{% trans "Change password" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'django_tasker_account:profile_mylocation' %}">{% trans "My location" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'django_tasker_account:profile_avatar' %}">{% trans "Avatar" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'django_tasker_account:logout' %}">{% trans "Log out" %}</a>
                    </li>
                </ul>
            </div>
            {% endif %}

            <div class="row">
                <div class="col">
                    {% block form %}{% endblock %}

                </div>
            </div>

            {% if not request.user.is_authenticated %}
            <hr>
            <div class="row">
                <div class="col">
                    <p class="mt-6 mb-3 text-muted text-center">
                        <a href="{% url 'django_tasker_account:oauth_google' %}?next={{ request.GET.next|default:'/' }}" class="btn btn-outline-primary">Google</a>
                        <a href="{% url 'django_tasker_account:oauth_yandex' %}?next={{ request.GET.next|default:'/' }}" class="btn btn-outline-primary">Yandex</a>
                        <a href="{% url 'django_tasker_account:oauth_mailru' %}?next={{ request.GET.next|default:'/' }}" class="btn btn-outline-primary">Mail.ru</a>
                    </p>

                    <p class="mt-6 mb-3 text-muted text-center">
                        <a href="{% url 'django_tasker_account:oauth_facebook' %}?next={{ request.GET.next|default:'/' }}" class="btn btn-outline-primary">Facebook</a>
                        <a href="{% url 'django_tasker_account:oauth_vk' %}?next={{ request.GET.next|default:'/' }}" class="btn btn-outline-primary">VK.com</a>
                    </p>
                    <p class="mt-5 mb-3 text-muted text-center">&copy; Django Tasker Account {{ YEAR }}</p>
                </div>
            </div>
            {% endif %}

        </div>

    </body>
</html>

django_tasker_account/templates/django_tasker_account/change_password.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Change" title="Change password" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/forgot_password.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Reset my password" title="Password reset" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/form.html
{% load i18n %}

<form class="form-signin" method="{{ method|default:"POST" }}" enctype="{{ enctype|default:"application/x-www-form-urlencoded" }}">
    {% csrf_token %}
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">{% trans title %}</h1>
    </div>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}

        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        <div class="form-group">
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form %}
        {% if field.field.widget.input_type == 'checkbox' %}
            <div class="form-group form-check">
                {{ field }}
                <label class="form-check-label" for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
            </div>
        {% else %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}

                {% for error in field.errors %}
                    <small id="{{ field.auto_id }}" class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">{% trans button %}</button>
</form>

django_tasker_account/templates/django_tasker_account/login.html
{% extends "django_tasker_account/base.html" %}
{% load i18n %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Log in" title="Log in" %}

    <div class="row form-signin">
        <a href="{% url 'django_tasker_account:forgot_password' %}">{% trans "Password reset" %}</a>
    </div>
{% endblock %}

django_tasker_account/templates/django_tasker_account/oauth_completion.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Save" title="Completion registration" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/profile.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Save" title="Personal info" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/profile_avatar.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Change" title="Change avatar" enctype="multipart/form-data" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/profile_change_password.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Change" title="Change password" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/profile_mylocation.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Change" title="My location" %}
{% endblock %}

django_tasker_account/templates/django_tasker_account/signup.html
{% extends "django_tasker_account/base.html" %}
{% block form %}
    {% include "django_tasker_account/form.html" with button="Sign Up" title="Sign Up" %}
{% endblock %}